apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ default "readability" .Values.deployment_name }}"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "readability" .Values.deployment_name }}"
    service-group: ui
    log-style: uwsgi
spec:
  replicas: 1
  template:
    metadata:
      labels:
        subsystem: "{{ .Values.labels.subsystem }}"
        container: "{{ default "readability" .Values.deployment_name }}"
        service-group: ui
        log-style: uwsgi
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: "{{ default "readability" .Values.deployment_name }}"
        image: arxiv/readability:{{ .Values.imageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.database.secret.name }}"
              key: "{{ .Values.database.secret.key }}"
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.redis.secret.name }}"
              key: "{{ .Values.redis.secret.key }}"
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.redis.secret.name }}"
              key: "{{ .Values.redis.secret.key }}"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.django.secret.name }}"
              key: "{{ .Values.django.secret.key }}"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: DJANGO_LOG_LEVEL
          value: "DEBUG"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "{{ default "readability" .Values.deployment_name }}-worker"
  namespace: "{{ .Values.namespace }}"
  labels:
    subsystem: "{{ .Values.labels.subsystem }}"
    container: "{{ default "readability" .Values.deployment_name }}-worker"
    service-group: backend
    log-style: celery
spec:
  replicas: 1
  template:
    metadata:
      labels:
        subsystem: "{{ .Values.labels.subsystem }}"
        container: "{{ default "readability" .Values.deployment_name }}-worker"
        service-group: backend
        log-style: celery
      annotations:
        prometheus.io/scrape: 'true'
    spec:
      containers:
      - name: arxiv-readability-worker
        image: arxiv/readability:{{ .Values.imageTag }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        command:
          - "sh"
          - "-c"
          - celery -A arxiv_html worker -l info
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.database.secret.name }}"
              key: "{{ .Values.database.secret.key }}"
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.redis.secret.name }}"
              key: "{{ .Values.redis.secret.key }}"
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.redis.secret.name }}"
              key: "{{ .Values.redis.secret.key }}"
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: "{{ .Values.django.secret.name }}"
              key: "{{ .Values.django.secret.key }}"
        - name: ALLOWED_HOSTS
          value: "*"
